// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="About the Artist"
          title="Mastery in Every Line"
          description="With over a decade of experience, we transform skin into high-end canvases using specialized 3D-depth techniques."
          imageSrc="http://img.b2bpic.net/free-photo/tattoo-master-preparing-sketch-tattoo_627829-12067.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
