// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Common Queries"
          title="Frequently Asked Questions"
          description="Find answers to all your concerns before booking."
          items={[
            {
              question: "How do I book a session?",
              answer: "Consultation first, then booking via our portal.",
            },
            {
              question: "What is the aftercare process?",
              answer: "Detailed instructions provided post-session.",
            },
            {
              question: "Are custom designs available?",
              answer: "Custom designs are our primary focus.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
