/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import AvatarGroup from "@/components/ui/AvatarGroup";

const primaryButton = {
  text: "Book Appointment",
  href: "#contact"
};
const secondaryButton = {
  text: "View Portfolio",
  href: "#works"
};

type HeroBillboardProps = {
  tag?: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  avatarsSrc?: string[];
  avatarsLabel?: string;
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const HeroInline = () => {
  return (
    <section aria-label="Hero section" className="relative pt-25 pb-20 md:pt-30 overflow-hidden" style={{ perspective: "1000px" }}>
      <HeroBackgroundSlot />
      {/* 3D Spatial Lighting Glows */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gradient-to-tr from-neutral-800/20 via-neutral-600/10 to-transparent rounded-full blur-[140px] pointer-events-none animate-pulse" />
      <div className="absolute top-10 right-10 w-72 h-72 bg-amber-500/5 rounded-full blur-[120px] pointer-events-none" />

      <div className="flex flex-col gap-12 md:gap-15 w-content-width mx-auto relative z-10">
        <div className="flex flex-col items-center gap-3 text-center">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-neutral-900/90 border border-neutral-700/80 shadow-[0_10px_25px_rgba(0,0,0,0.8)] backdrop-blur-md text-xs font-mono tracking-widest text-neutral-300 uppercase mb-2 transform transition-transform hover:scale-105 hover:border-amber-500/50">
            <span className="flex h-2 w-2 rounded-full bg-amber-400 animate-ping" />
            <span>Luxury Tattoo Artistry</span>
          </div>

          <TextAnimation
            text={"Defining Luxury Ink"}
            variant={"fade-blur"}
            gradientText={true}
            tag="h1"
            className="md:max-w-8/10 text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-center text-balance drop-shadow-[0_15px_25px_rgba(0,0,0,0.9)]"
          />

          <TextAnimation
            text={"Exquisite bespoke tattooing for the discerning individual. High-precision linework, custom depth, and timeless luxury artistry."}
            variant={"fade-blur"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-balance text-neutral-400"
          />

          <div className="flex flex-wrap justify-center gap-4 mt-3 md:mt-4">
            <Button text={primaryButton.text} href={primaryButton.href} variant="primary" className="shadow-[0_10px_30px_rgba(255,255,255,0.15)] hover:shadow-[0_15px_40px_rgba(255,255,255,0.25)] hover:scale-105 transition-all duration-300" />
            <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary" animationDelay={0.1} className="shadow-[0_10px_25px_rgba(0,0,0,0.6)] hover:scale-105 hover:border-neutral-500 transition-all duration-300" />
          </div>
        </div>

        {/* 3D Depth Card Container with Layered Tilt & Floating Overlay Badges */}
        <div className="relative group w-full max-w-5xl mx-auto" style={{ transformStyle: "preserve-3d" }}>
          {/* Back floating perspective offset shadow card */}
          <div className="absolute inset-0 rounded-2xl bg-neutral-900/40 border border-neutral-700/40 transform translate-y-3 translate-x-3 scale-[0.99] group-hover:translate-y-5 group-hover:translate-x-5 transition-all duration-500 ease-out" />

          {/* Main Elevated Card with Interactive Depth */}
          <ScrollReveal variant="fade-blur" delay={0.2} className="relative w-full p-3 xl:p-4 card rounded-2xl overflow-hidden border border-neutral-700/80 shadow-[0_25px_60px_-15px_rgba(0,0,0,0.95)] backdrop-blur-xl group-hover:border-neutral-500/80 group-hover:-translate-y-2 transition-all duration-500">
            <ImageOrVideo imageSrc={"http://img.b2bpic.net/free-photo/portrait-tattoo-pierced-young-man-holding-carnation-flower-joined-hands_23-2148121948.jpg"} className="aspect-4/5 md:aspect-video rounded-xl object-cover filter contrast-[1.05] brightness-95 group-hover:scale-[1.02] transition-all duration-700" />
            
            {/* Interactive 3D Overlay Glass Cards */}
            <div className="absolute top-6 right-6 bg-neutral-950/80 border border-neutral-700/80 text-neutral-200 px-4 py-2 rounded-xl text-xs font-mono backdrop-blur-xl shadow-2xl transition-all duration-300 group-hover:scale-105 group-hover:border-amber-500/60 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-400" />
              <span>Hyper-Depth Realism 3D</span>
            </div>

            <div className="absolute bottom-6 left-6 right-6 md:right-auto md:max-w-md p-4 rounded-xl bg-neutral-950/85 border border-neutral-800 backdrop-blur-xl shadow-2xl transition-all duration-300 group-hover:translate-y-[-4px] group-hover:border-neutral-700">
              <div className="text-xs uppercase font-mono tracking-wider text-amber-400 mb-1">Interactive Showcase</div>
              <h3 className="text-base font-bold text-foreground">Spatial Anatomical Ink</h3>
              <p className="text-xs text-neutral-400 mt-1">Multi-layered shading tailored to natural body contours for dynamic 3D depth perception.</p>
            </div>
          </ScrollReveal>
        </div>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" data-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
