// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import { Award, CheckCircle, Star } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsIconCards
          tag="Proven Results"
          title="By The Numbers"
          description="Years of craft and countless satisfied collectors."
          metrics={[
            {
              icon: Award,
              title: "Awards Won",
              value: "12",
            },
            {
              icon: Star,
              title: "Years Active",
              value: "10+",
            },
            {
              icon: CheckCircle,
              title: "Completed Pieces",
              value: "800+",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
