// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "process" section.

import React from 'react';
import FeaturesMediaCarousel from '@/components/sections/features/FeaturesMediaCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProcessSection(): React.JSX.Element {
  return (
    <div id="process" data-section="process">
        <SectionErrorBoundary name="process">
              <FeaturesMediaCarousel
          tag="The Process"
          title="Beyond the Ink"
          description="A meticulous, highly professional journey from initial consultation to final healed results."
          items={[
            {
              title: "Concept Design",
              description: "Collaborative sketching and digital proofing.",
              buttonIcon: "Sparkles",
              imageSrc: "http://img.b2bpic.net/free-photo/braless-woman-working-indoor_23-2150490520.jpg",
            },
            {
              title: "Sterile Excellence",
              description: "Unmatched industry safety and clinical standards.",
              buttonIcon: "Shield",
              imageSrc: "http://img.b2bpic.net/free-photo/women-hanging-out-together_53876-47008.jpg",
            },
            {
              title: "Precision Artistry",
              description: "Expert application using advanced instrumentation.",
              buttonIcon: "Zap",
              imageSrc: "http://img.b2bpic.net/free-photo/animated-screwdriver-with-screw-banner_23-2149911045.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
