// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "proof" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProofSection(): React.JSX.Element {
  return (
    <div id="proof" data-section="proof">
        <SectionErrorBoundary name="proof">
              <SocialProofMarquee
          tag="Industry Recognitions"
          title="Trusted by Peers"
          description="Featured in top-tier industry publications and recognized by global artist communities."
          names={[
            "INK WORLD",
            "ARTISTIC UNION",
            "GLOBAL TATTOO MASTERS",
            "STUDIO EXCELLENCE",
            "MODERN AGENCY",
            "INK PROFESSIONALS",
            "TATTOO SOCIETY",
            "CREATIVE COMMUNITY",
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
