// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Collectors' Voices"
          title="Enduring Impressions"
          description="What our clients say about the experience of working with us."
          testimonials={[
            {
              name: "Alice R.",
              role: "Creative Lead",
              quote: "The detail is unbelievable. Absolute mastery.",
              imageSrc: "http://img.b2bpic.net/free-photo/ortrait-lady-pointing-up-casual-clothes-looking-confident-front-view_176474-57069.jpg",
            },
            {
              name: "Michael S.",
              role: "Entrepreneur",
              quote: "I've never seen such precision. Truly a luxury service.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-woman-holding-coffee-cup_23-2149628821.jpg",
            },
            {
              name: "Sarah L.",
              role: "Collector",
              quote: "The entire process was professional and welcoming.",
              imageSrc: "http://img.b2bpic.net/free-photo/tattoo-artist-doing-her-job-medium-shot_23-2149445983.jpg",
            },
            {
              name: "David W.",
              role: "Architect",
              quote: "The geometry and flow of the design are impeccable.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-tattoo-artist-doing-his-job_23-2149525943.jpg",
            },
            {
              name: "Elena M.",
              role: "Designer",
              quote: "Simply the best studio experience I've had.",
              imageSrc: "http://img.b2bpic.net/free-photo/black-friday-sale-black-label-collection_24972-1216.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
