// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "works" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function WorksSection(): React.JSX.Element {
  return (
    <div id="works" data-section="works">
        <SectionErrorBoundary name="works">
              <FeaturesRevealCardsBento
          tag="Featured Works"
          title="Curated Artistry"
          description="A glimpse into our most complex and precise custom pieces."
          items={[
            {
              title: "Geometric Depth",
              description: "Complex lines creating deep 3D illusions.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/black-white-portrait-mermaid_23-2151718524.jpg",
            },
            {
              title: "Portrait Precision",
              description: "Capturing realism in every subtle shade.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/experienced-tattoo-artist-working-client-tattoo_23-2149479253.jpg",
            },
            {
              title: "Ornate Masterpiece",
              description: "Highly detailed traditional patterns refined.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/golden-lights-reflected-champagne-bottle_23-2148339624.jpg",
            },
            {
              title: "Minimalist Grace",
              description: "Subtle, refined luxury for everyday wear.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/jewellery-skull-bangle-background-with-place-text-banner-fashion-accessories_460848-14683.jpg",
            },
            {
              title: "Blackwork Art",
              description: "Deep bold shadows for high impact contrast.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/shirtless-young-man-with-tattoo-his-body-holding-sunflower-hand-against-grey-background_23-2148121940.jpg",
            },
            {
              title: "Botanical Flow",
              description: "Natural elements rendered with fluid motion.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/monochrome-portrait-man-with-tattoos_23-2150774485.jpg",
            },
            {
              title: "Abstract Layers",
              description: "Unique multi-layered creative concepts.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/ink_1417-1956.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
